'------------------------------------------------------------------------------
' <auto-generated>
'     Ten kod został wygenerowany przez narzędzie.
'
'     Zmiany w tym pliku mogą być przyczyną niepoprawnego zachowania i zostaną utracone w przypadku
'     ponownego wygenerowania kodu.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

